### ISSUE TITLE
feat: get_bpm

### ISSUE THREAD

**Issue by raphaelDkhn** [cienicera/Koji#11]
Extract the tempo (in BPM) from the Midi data.
```
fn get_bpm(self: @Midi) -> u32;
```

**Comment by caseywescott** [comment]
First draft [Here](https://github.com/cienicera/Koji/blob/bfb93f51042424e948115a008138fa240f4f432b/src/midi/core.cairo#L125) . Currently assumes tempo doesn't change - May be best to allow returning n tempos or tempos at a given time.
