### ISSUE TITLE
Udate Koji to Cairo 2.6.x

### ISSUE THREAD

**Issue by raphaelDkhn** [cienicera/Koji#35]
We need to update Koji to scarb/cairo 2.6.x. It currently supports scarb 2.3.1.

**Comment by AryanGodara** [comment]
@raphaelDkhn Can I take this one, I worked on a similar issue recently, and I'd love to be able to contribute here

**Comment by AryanGodara** [comment]
@raphaelDkhn After running `scarb build` I've been getting multiple compiler errors and warnings, mainly related to Copy, or Drop traits not being implemented by `orion::numbers::FP32x32` or other imports.

I've been trying to fix this, but did this problem already exist, or am I doing something wrong?

**Comment by raphaelDkhn** [comment]
> @raphaelDkhn After running `scarb build` I've been getting multiple compiler errors and warnings, mainly related to Copy, or Drop traits not being implemented by `orion::numbers::FP32x32` or other imports.
> 
> I've been trying to fix this, but did this problem already exist, or am I doing something wrong?

You have only warnings or also errors? 
The warnings are normal, as some dependent libraries also have compiler warnings and they didn't fix it.

**Comment by AryanGodara** [comment]
There are errors, like these ones:
<img width="883" alt="image" src="https://github.com/cienicera/Koji/assets/65490434/a1277c0f-c8e1-4f7d-81db-325f028d47c2">
<img width="1077" alt="image" src="https://github.com/cienicera/Koji/assets/65490434/4c0e1120-818f-4331-9623-44465013e6ad">

**Comment by caseywescott** [comment]
@AryanGodara made some good changes (that LGTM) to update to 2.6.3 : https://github.com/cienicera/Koji/pull/39  
@raphaelDkhn I'll defer to you on this one particular merge.
