### ISSUE TITLE
feat: Implement Euclidean rhythm algorithm for time.cairo

### ISSUE THREAD

**Issue by caseywescott** [cienicera/Koji#37]
# Feature Request

Implement the Bjorklund/Euclidean rhythm algorithm which is a method for generating rhythms that evenly distribute a certain number of pulses (notes or beats) over a given number of steps (time intervals). This algorithm is particularly useful for creating rhythms with an even, balanced feel.

More info:
https://en.wikipedia.org/wiki/Euclidean_rhythm

**Describe Preferred Solution**

Here is a Typescript implementation:

function euclideanrhythm(n: number, k: number): number[] {
  const pattern: number[] = Array(n).fill(0);
  const counts: number[] = Array(k).fill(Math.floor(n / k));

  const remainders = n % k;
  let index = 0;

  for (let i = 0; i < remainders; i++) {
    pattern[index] = 1;
    index += (counts[i] + 1);
  }

  for (let i = remainders; i < k; i++) {
    pattern[index] = 1;
    index += counts[i];
  }

  return pattern;
}

// Example usage
const n = 8; // Total steps
const k = 2; // Number of pulses

const pattern = euclideanrhythm(n, k);
// Another example
const pattern2 = euclideanrhythm(7, 3);

console.log(pattern); // returns -> [1, 0, 0, 0, 1, 0, 0, 0]
console.log(pattern2);  // returns -> [1, 0, 0, 1, 0, 1, 0] 

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by aguzmant103** [comment]
@caseywescott just messaged over TG, would love to pick this one!

**Comment by caseywescott** [comment]
Hey @aguzmant103 - How is it going on this one? Let me know if you need anything!

**Comment by aguzmant103** [comment]
Hey @caseywescott thanks for checking in! I have a clear understanding on how to solve it however I've been battling with many noob issues in Cairo. Hope to have a draft PR by EOD today, and finish the PR for review end of week tops! Lmk if that's good for you

**Comment by caseywescott** [comment]
No worries and no rush mate @aguzmant103 . Thanks for jamming on it!

**Comment by aguzmant103** [comment]
@caseywescott PR submitted! 
I think I'll still have to work on some optimizations, style format and likely expanding test cases. But it has a working -functioning euclidean rhythm generator (: looking forward for feedback!

**Comment by aguzmant103** [comment]
@caseywescott just realized, shall this be inside time.cairo file? Or called as an individual module?

**Comment by caseywescott** [comment]
I think euclidean.cairo is best! I think it makes sense for it to stand on it's own. I will check it out soon!

**Comment by caseywescott** [comment]
Hey @aguzmant103! Great work on the code. I made some changes to make it run smoother and handled all of the edge case like when n ==0 or k>n as well as wrote tests for that. I was going to make a new pr for the update (giving you all credit) but if I can make a pr on your repo we can push/merge from there. Either way you will get the credit. Let me know what works best for you - You did a great job!

**Comment by andyguzmaneth** [comment]
@caseywescott thanks for the support! As the conversation on the issues #46 #54 seems we can mark this one as done. Tysm! :)
