### ISSUE TITLE
feat: React SoundFont Player for Cairo MIDI contracts

### ISSUE THREAD

**Issue by caseywescott** [cienicera/Koji#40]
# Feature Request

React component that supports loading and playing MIDI files from Cairo contracts using SoundFont files for playback. Component should provide an interface to query a Cairo contract to retrieve MIDI data dynamically or from the Cairo-to-Midi transpiler or directly from the contract. 

Ideally, it would be great to enter an address which makes a call to retrieve the MIDI data.

Here are some soundfonts for testing: https://github.com/caseywescott/soundfonts

This was an older, bloated, version I made for Cairo0: 
https://github.com/caseywescott/KOJI/tree/master

**Comment by Xaxxoo** [comment]
Please assign this to me.

**Comment by caseywescott** [comment]
This could be super lightweight - The idea is have something small and simple so that apps/websites can load Midis from Cairo contracts and play them with a soundfont. I know there there are some super simple soundfont/midi players we could fork for this.

**Comment by caseywescott** [comment]
Hey @Xaxxoo - I've tried to run the code with the following commands but have been unable to get it running: 
npm install --legacy-peer-deps
npm start
Are these the right commands to get it running? It says there are missing scripts

**Comment by Xaxxoo** [comment]
Yes. those are the commands.

Side: I need the contract address to connect the frontend and the contract.

**Comment by caseywescott** [comment]
Huh - I haven't been able to get it running. I will try again. I think this is probably a good place to keep things as the calling from a contract is a step further than the rest of the code.

**Comment by caseywescott** [comment]
Hey! I got this running! Looks good! Huge shoutout for your awesome pull request! Thank you so much for contributing! Stoked!
