### ISSUE TITLE
feat: Implement SysEx & ProgramChange Messages

### ISSUE THREAD

**Issue by caseywescott** [cienicera/Koji#42]
# Feature Request

Add SysEx & ProgramChange messages to available types.

ProgramChanges are used to assign General MIDI (GM) instruments in MIDI sequences

System Exclusive (SysEx) messages in MIDI are used for transferring specific manufacturer-specific or device-specific data between MIDI-compatible devices. These messages are not part of the standard MIDI protocol but are instead used for proprietary purposes by manufacturers to implement additional features or functionalities beyond what is defined in the MIDI standard. They will come in handy for art installations. 

Add SysEx & ProgramChange message functionality to MidiTrait
**Describe the Feature Request**

**Comment by Xaxxoo** [comment]
@caseywescott Please can you assign this to me?

**Comment by caseywescott** [comment]
Ideally we these messages to MIDItrait such that all of the MIDItrait functions' loops/match functions account for these messages as well.

For example this loop should also append any SysEx or ProgramChange messages as well as the others.
https://github.com/cienicera/Koji/blob/ed266ba083b11f0728b61c35de93ec495d9f71d7/src/midi/core.cairo#L78

**Comment by caseywescott** [comment]
I've assigned all these that you requested!! Stoked!!!

**Comment by caseywescott** [comment]
I think these are the right type definitions: 

// Program Change

#[derive(Copy, Drop)]
struct ProgramChange {
    channel: u8,
    program: u8, // Program number (0 to 127)
    time: FP32x32
}

// Define SysEx struct - I think the data should be a Span<u8> but open to your ideas!

#[derive(Copy, Drop)]
struct SysEx {
    data: Span<u8> // Data bytes for SysEx message
}

**Comment by caseywescott** [comment]
Issue implemented and merged here: 
https://github.com/cienicera/Koji/pull/52
