### ISSUE TITLE
feat: change_tempo

### ISSUE THREAD

**Issue by raphaelDkhn** [cienicera/Koji#9]
Alter the tempo of the Midi data.
```
    fn change_tempo(self: @Midi, new_tempo: u32) -> Midi;
```

**Comment by caseywescott** [comment]
[Here](https://github.com/cienicera/Koji/blob/6ee7f5199023532fa924fef4df333fd36ff93fd8/src/midi/core.cairo#L69C1-L69C1) is an implementation of change_tempo. Let me know if I should make any modifications to the pattern.
